disabled: false
scan-type: source
ignore:
  - vulnerability: GHSA-mh99-v99m-4gvg
    include-aliases: true
    reason: 'Unfixable npm transitive vulnerability: unknown (unknown severity) as of 2026-09-17'
  - vulnerability: GHSA-rgw5-rvv9-x895
    include-aliases: true
    reason: 'Unfixable npm transitive vulnerability: unknown (unknown severity) as of 2026-09-17'
output:
  - table
  - json
search:
  scope: squashed
quiet: false
check-for-app-update: false
