disabled: false

# For repos that do not produce a container image, use source scanning
scan-type: source

ignore:

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
